### ISSUE TITLE
DateTime with m-d-y

### ISSUE THREAD

**Issue by djomla1989** [NowCerts/NowCerts-PHP-SDK#3]
https://github.com/NowCerts/NowCerts-PHP-SDK/blob/2f72531e0e3265c9d1262c785998e577b0df80ca/src/Insured.php#L251

Hi,
I have issue using this.
This is error
`DateTime::__construct(): Failed to parse time string (06-25-1981) at position 0 (0)`

I guess it's problem with date format. DateTime will see this as D-M-Y, because of "-"

Can you confirm this?

**Comment by jacobembree** [comment]
You're quite right.  You can create your own `DateTime` object and pass that as an argument rather than passing the string "06-25-1981".  To use a non-standard format you can use [DateTime::createFromFormat](https://www.php.net/manual/en/datetime.createfromformat.php) and pass the result as an argument to `\NowCerts\Insured::__construct`.

**Comment by djomla1989** [comment]
Yes, we can do that, but we are using `\NowCerts\Insured::getInsureds()` and "06-25-1981" is api response.

> To use a non-standard format you can use DateTime::createFromFormat and pass the result as an argument to \NowCerts\Insured::__construct.

In that case we should need to go through each api response row and modify date fields.

**Comment by jacobembree** [comment]
We'll have to override the `__construct`` method in `\NowCerts\DateTime` then.  I'll try to do that soon.

**Comment by jacobembree** [comment]
Done.  Let me know if this didn't fix it.
